name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Setup Docker
      uses: docker/setup-buildx-action@v2

    - name: Enable RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Run LocalXpose Tunnel with Docker
      run: |
        docker pull localxpose/localxpose:latest
        docker run -d --name loclx -e LOCLX_TOKEN=${{ secrets.LOCALXPOSE_TOKEN }} localxpose/localxpose:latest tcp 3389
      env:
        LOCLX_TOKEN: ${{ secrets.LOCALXPOSE_TOKEN }}

    - name: Verify LocalXpose Tunnel
      run: docker ps
