name: RDP with LocalXpose

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download LocalXpose
      run: Invoke-WebRequest https://localxpose.io/localxpose_windows_amd64.zip -OutFile lx.zip

    - name: Extract LocalXpose
      run: Expand-Archive lx.zip

    - name: Enable RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Start Tunnel
      run: .\localxpose.exe tunnel tcp --port 3389 --auth-token $Env:LX_TOKEN
      env:
        LX_TOKEN: ${{ secrets.LOCALXPOSE_TOKEN }}
