name: Run Telegram Bot

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Menjalankan secara manual melalui GitHub Actions UI

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Menambahkan step untuk mengekstrak file ZIP terlebih dahulu
    - name: Extract ZIP file
      run: |
        echo "Extracting ZIP file"
        unzip guardian of angel.zip -d ./extracted_files

    # Menambahkan step untuk membuka folder setelah file diekstrak
    - name: Change Directory to Extracted Folder
      run: |
        echo "Changing directory to extracted files"
        cd ./extracted_files

    # Install dependencies menggunakan npm pada langkah terakhir
    - name: Install dependencies
      run: |
        cd ./extracted_files
        npm install

    # Menjalankan bot dan membaca config.js
    - name: Run Telegram Bot with config.js
      run: |
        cd ./extracted_files
        node index.js
      env:
        TELEGRAM_BOT_TOKEN: $(node -e "const config = require('./config.js'); console.log(config.BOT_TOKEN);")
        TELEGRAM_USER_ID: $(node -e "const config = require('./config.js'); console.log(config.OWNER_ID);")
